language: node_js
node_js:
  - "8"
install:
  npm install
addons:
  postgresql: 9.6
before_script:
  - psql -c 'create database instagram-test;' -U postgres
  - node test/seed-testdb.js
  - node server/index.js & sleep 30
script: 
  - npm test
