language: node_js
node_js:
  - "8"
install:
  npm install
addons:
  postgresql: 9.6
before_script:
  - psql -c 'create database instagram;' -U postgres
  - knex migrate:latest interactions & sleep 10
  - knex migrate:rollback interactions & sleep 10
  - knex migrate:latest interactions & sleep 10
  - node test/seed-testdb.js & sleep 90
  - node server/index.js & sleep 30
script: 
  - npm test
